### ISSUE TITLE
User profile

### ISSUE THREAD

**Issue by richardvdhorst** [dealport/dealport#19]
A public page about the user. 

Available trough a "vanity url". domain/username. For example: dealport.co/richardvanderhorst
- [x] Support for named entities that reference a user (vanity url)
- [ ] #53 Set up sharejs for `user`
- [ ] #54 Editable page that displays information about a user
