### ISSUE TITLE
Company detail page

### ISSUE THREAD

**Issue by Joris-van-der-Wel** [dealport/dealport#20]
- [x] Vanity urls for companies (without conflicts between different entities)
- [x] Routing & Controllers for the detail page
- [x] Display the same fields as in a CompanyGridItem in the header
- [x] Field for product info
- [ ] #21 Link a `User` to a company (founders, team members, investors, etc) : Depends on #19
- [ ] #22 List of job vacancies
